
#version: '3'
#services:
  #web:
   # image: "rl640/image.5.23"
    #ports:
     # - "8080:80"

version: "3.7"
services:
    db-1:
        container_name: postgres_contsiner
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres-db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    pgadmin-1:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8081:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        #links:
          #  - "postgres-db:pgsql-server"
volumes:
    postgres-db-data:
    pgadmin-data: